### ISSUE TITLE
To-do list for myself

### ISSUE THREAD

**Issue by corp-0** [corp-0/AdvancedTowing#1]
- [ ] Add localization support.
- [ ] Add ace menu interactions support.
- [ ] Check if player has the rope item to permit attachment (optional).
- [ ] Allow to attach from front or back of the vehicle.
